services:
    utils.facebook.feed_catcher:
        class: FrontBundle\Utils\Facebook\FacebookFeedCatcher
        arguments: ["@utils.facebook_app", %facebook_page_id%, %starting_date%]

    utils.facebook_app:
        class: Facebook\FacebookApp
        arguments: [%facebook_app_id%, %facebook_app_secret%]

    utils.twitter.tweets_catcher:
        class: FrontBundle\Utils\Twitter\TwitterTweetsCatcher
