services:
    utils.facebook.feed_catcher:
        class: FrontBundle\Utils\Facebook\FacebookFeedCatcher
        arguments: ["@utils.facebook_app", %facebook-page-id%]

    utils.facebook_app:
        class: Facebook\FacebookApp
        arguments: [%facebook-app-id%, %facebook-app-secret%]
